services:
  db: 
    image: postgres:alpine3.14
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=productDb
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./stundenplaner_service/src/main/resources/postgres:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    restart: always
    volumes:
      - ./stundenplaner_service/src/main/resources/pgadmin:/root/.pgadmin
  api:
    build:
      context: ./stundenplaner_service
      dockerfile: ./docker/Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
  web:
    build:
      context: ./stundenplaner_app
      dockerfile: ./docker/Dockerfile
    expose:
      - "80"
  reverseproxy:
    image: nginx
    expose:
      - "80"
      - "443"
      - "8080"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx:/etc/nginx
      - ./proxy/ssl/private:/etc/ssl/private
      - ./proxy/nginx/log:/etc/log
    depends_on:
      - "web"
      - "api"