package de.hofuniversity.minf.stundenplaner;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

/**
 * @author autogenerated
 * Spring Boot starter class
 */
@Slf4j
@SpringBootApplication
public class TimetableApplication implements WebMvcConfigurer {

    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**").allowedMethods("GET", "POST", "PUT", "DELETE");
        // TODO: 26.10.21 reconfigure for safer env
    }

    public static void main(String[] args) {
        log.trace("Starting application");
        SpringApplication.run(TimetableApplication.class, args);
    }

}
