package de.hofuniversity.minf.stundenplaner;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * @author autogenerated
 * Spring Boot starter class
 */
@Slf4j
@SpringBootApplication
public class TimetableApplication {

	public static void main(String[] args) {
		log.trace("Starting application");
		SpringApplication.run(TimetableApplication.class, args);
	}

}
